title: Matthew Love
description: >- 
  Programming and other technical stuff.
baseurl: "" 
url: "https://nukethebees.com/" 

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

theme: null

include:
  - robots.txt
  - BingSiteAuth.xml

header_links:
  - title: About
    url: /about/
  - title: C++
    url: /cpp/
  - title: Assembly
    url: /asm/
  - title: Blender
    url: /blender/
  - title: misc
    url: /misc/