title: NukeTheBees
description: >-
  Programming and other technical stuff.
baseurl: ""
url: "https://nukethebees.com"
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  auto_ids: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

theme: null

include:
  - robots.txt
  - BingSiteAuth.xml

permalink: /:title/

collections:
  unreal_notes:
    output: true
    permalink: /unreal/notes/:name/
  blender_notes:
    output: true
    permalink: /blender/notes/:name/
  dev_log:
    output: true
    permalink: /dev-log/:name/

header_links:
  - title: About
    url: /about/
  - title: "Unreal Engine"
    url: /unreal/
  - title: "Blender"
    url: /blender/
  - title: "Dev log"
    url: /dev-log/

category_pages:
  excluded:
    - unreal
    - blender
  manual_links:
    - title: Unreal Engine
      url: /unreal/
    - title: Blender
      url: /blender/
